name: Generate Readme Doc
on:
  workflow_dispatch:
  push:
    paths:
      - '*.json'
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
     - uses: 'phantomcyber/dev-cicd-tools/github-actions/generate-doc@mpan/PAPP-29363'
       with:
         GITHUB_TOKEN: ${{ secrets.SOAR_APPS_TOKEN }}
